id: DA8CAB8A0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-07T13:50:58+00:00'
last_modified: '2022-05-30T04:05:12.409696+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    aba4:
      image_group_id: I1PD95938
      title: དགེ་སྦྱོང་གི་ཀཱ་རི་ཀཱ་ལྔ་བཅུ་པ་མདོ་ཙམ་དུ་བཤད་པ།
      total_pages: 1484
      order: 93
      base_file: aba4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
